### ISSUE TITLE
Bugs fix in editing profile and event

### ISSUE THREAD

**Issue by ttxking** [jix-666/jix#57]
- Users can't edit their info if they don't upload a profile picture again
- When users uploaded their profile picture, they can't still edit
- Users can't edit event others detail if they don't change the name.

**Comment by nicenicegame** [comment]
The 3rd problem `Users can't edit event others detail if they don't change the name` has been fixed.

**Comment by ttxking** [comment]
> * Users can't edit their info if they don't upload a profile picture again
> * When users uploaded their profile picture, they can't still edit
> * Users can't edit event others detail if they don't change the name.

Users can edit everything now
