### ISSUE TITLE
Add Iteration 7 to Project Wiki and README

### ISSUE THREAD

**Issue by ttxking** [jix-666/jix#58]
* Add Iteration 7 detail to Project Wiki 
* Add Iteration 7 link to README

**Comment by ttxking** [comment]
Iteration 7 Plan is now shown on README

**Comment by bemyXmas** [comment]
- Add and update Iteration 7 detail to Project Wiki
- Add Iteration 7 link to README
After check through all updated links and detail, I think it's fine now.
