### ISSUE TITLE
Problem about date.

### ISSUE THREAD

**Issue by Ing140943** [jix-666/jix#61]
I try to use the application with many functions are working very well but I  found some minor bug. The bug is when I create some event the date of the day that I create is present but I make the appointment last year and it approves. Ex I create an event on 29 Nov 2020 but the appointment is 29 Nov 2019. I think it will be confused with other people because sometimes the user might choose the wrong year like me.

**Comment by ttxking** [comment]
Thank you for your suggestion! We'll fix it ASAP.

**Comment by ttxking** [comment]
The backdate is now disabled!
