### ISSUE TITLE
cannot edit event

### ISSUE THREAD

**Issue by metaras** [jix-666/jix#62]
![image](https://user-images.githubusercontent.com/59819639/100545392-315f3500-328e-11eb-8836-152be7d2dc1d.png)
![image](https://user-images.githubusercontent.com/59819639/100545424-505dc700-328e-11eb-84c6-d2bcc21adc95.png)
cannot change picture, name, date, description. error bar was appear after update

**Comment by ttxking** [comment]
We're fixing it ASAP

**Comment by nicenicegame** [comment]
We've already fixed this problem, thank you.
