### ISSUE TITLE
Can not install requirement.txt

### ISSUE THREAD

**Issue by Jomsaruj** [jix-666/jix#65]
I'm currently use MAC operating system. I found a problem when I run this command `pip install -r requirements.txt`.

<img width="706" alt="1" src="https://user-images.githubusercontent.com/59832457/100547071-64f28d00-3297-11eb-9c55-d8e868ffa610.png">

I guess the problem is in line 39. I can not install `psycopg2==2.8.5` . see similar issue at [issue](https://stackoverflow.com/questions/39767810/cant-install-psycopg2-package-through-pip-install-is-this-because-of-sierra)

**Comment by ttxking** [comment]
OK, we are trying to find a solution

**Comment by ttxking** [comment]
We updated the project installation README.MD. It's able to install now
