### ISSUE TITLE
Can't login with Facebook account

### ISSUE THREAD

**Issue by bhatara007** [jix-666/jix#68]
When I tried to log in with my Facebook account the login page shows this:

URL: https://jix.herokuapp.com/accounts/login/ and click "Sign in with Facebook"
![image](https://user-images.githubusercontent.com/59830751/100925148-32a19380-3514-11eb-807c-0de0d9a3c010.png)

**Comment by ttxking** [comment]
We're concerned with this problem, We'll fix it as soon as possible

**Comment by ttxking** [comment]
We removed the Facebook and Twitter for now
