### ISSUE TITLE
Profile page username and email have textfield display and some design suggestion.

### ISSUE THREAD

**Issue by Sahadporn** [jix-666/jix#69]
URL: https://jix.herokuapp.com/users/sirapop.ku/

In the user profile page the username and email information are display as textfield. You can write over the username and email information of any user account.

How to reproduce the problem:
Go to any user profile page. (You don't even need to log in.)

![image](https://user-images.githubusercontent.com/59825486/100892512-fc9ce900-34ec-11eb-9b86-ddc60eb69ff0.png)
![image](https://user-images.githubusercontent.com/59825486/100892701-3241d200-34ed-11eb-864c-3fb1d9af90f7.png)
---

URL: https://jix.herokuapp.com/events/sport/lets-go-camping/

The text container for event descriptions is not word-warp.

How to reproduce the problem:
1. Log in and create a new event.
2. In the description box type more than 170 characters.

![image](https://user-images.githubusercontent.com/59825486/100894644-4ab2ec00-34ef-11eb-9ae6-b74682fd23d7.png)

**Comment by ttxking** [comment]
The second problem is a defect, we'll fix it as soon as possible. The first one, however, is duplicated with https://github.com/jix-666/jix/issues/71 and we don't consider it as a deflect. You can write whatever you want, you can't submit anything!

**Comment by bemyXmas** [comment]
The second problem is now fixed!
