### ISSUE TITLE
Other: It look like the server will alway return Error (500) for user who enter javascript as his name

### ISSUE THREAD

**Issue by ZEZAY** [jix-666/jix#70]
I try to enter my username with javascript, and then every single page (when I still log in), returns Server Error (500).
It works normally when I didn't login thoungh.

URL: https://jix.herokuapp.com/

![image](https://user-images.githubusercontent.com/44806732/100939622-2e33a580-3529-11eb-97d6-de1222f4e73c.png)

**Comment by ttxking** [comment]
I don't understand you.

**Comment by ZEZAY** [comment]
Then just try it yourself.
1. go to your profile, edit it.
2. enter username with 
`<script>
  alert("Hello! I am an alert box!");
</script>`
3. then click Update.

**Comment by ttxking** [comment]
Ok, I will try, but before opening issue next time please be more specific and add a way to reproduce.
