### ISSUE TITLE
I found the Post form display as a user profile and send it!

### ISSUE THREAD

**Issue by ZEZAY** [jix-666/jix#71]
I found that the site uses Post form on the user profile page, so I use inspect to edit something.
And I see that I can send the edit of that profile, even though it gets rejected.

![image](https://user-images.githubusercontent.com/44806732/100915993-b99c3f00-3507-11eb-98c3-6bb57430799f.png)

**Comment by ttxking** [comment]
Well, It doesn't allow you to submit anyway, I don't see the problem here.
