### ISSUE TITLE
Functionality: I found bad link on https://jix.herokuapp.com/events/ page

### ISSUE THREAD

**Issue by ZEZAY** [jix-666/jix#72]
I used selenium then found a bad link.
Url: https://jix.herokuapp.com/events/

![image](https://user-images.githubusercontent.com/44806732/100914031-1d713880-3505-11eb-82ff-77b3736b703b.png)

![image](https://user-images.githubusercontent.com/44806732/100914048-206c2900-3505-11eb-9818-b0b06d82a0d1.png)

**Comment by ttxking** [comment]
The bad link is now removed.
